//
//  CSSColor.swift
//  PhantomKit
//
//  Created by Pawel Wiszenko on 27.04.2021.
//  Copyright © 2021 Pawel Wiszenko. All rights reserved.
//

import SwiftUI

// Reference: https://www.w3schools.com/cssref/css_colors.asp
public enum CSSColor {
    public static let aliceBlue = Color(hex: 0xF0F8FF)
    public static let antiqueWhite = Color(hex: 0xFAEBD7)
    public static let aqua = Color(hex: 0x00FFFF)
    public static let aquamarine = Color(hex: 0x7FFFD4)
    public static let azure = Color(hex: 0xF0FFFF)
    public static let beige = Color(hex: 0xF5F5DC)
    public static let bisque = Color(hex: 0xFFE4C4)
    public static let black = Color(hex: 0x000000)
    public static let blanchedAlmond = Color(hex: 0xFFEBCD)
    public static let blue = Color(hex: 0x0000FF)
    public static let blueViolet = Color(hex: 0x8A2BE2)
    public static let brown = Color(hex: 0xA52A2A)
    public static let burlyWood = Color(hex: 0xDEB887)
    public static let cadetBlue = Color(hex: 0x5F9EA0)
    public static let chartreuse = Color(hex: 0x7FFF00)
    public static let chocolate = Color(hex: 0xD2691E)
    public static let coral = Color(hex: 0xFF7F50)
    public static let cornflowerBlue = Color(hex: 0x6495ED)
    public static let cornsilk = Color(hex: 0xFFF8DC)
    public static let crimson = Color(hex: 0xDC143C)
    public static let cyan = Color(hex: 0x00FFFF)
    public static let darkBlue = Color(hex: 0x00008B)
    public static let darkCyan = Color(hex: 0x008B8B)
    public static let darkGoldenRod = Color(hex: 0xB8860B)
    public static let darkGray = Color(hex: 0xA9A9A9)
    public static let darkGreen = Color(hex: 0x006400)
    public static let darkKhaki = Color(hex: 0xBDB76B)
    public static let darkMagenta = Color(hex: 0x8B008B)
    public static let darkOliveGreen = Color(hex: 0x556B2F)
    public static let darkOrange = Color(hex: 0xFF8C00)
    public static let darkOrchid = Color(hex: 0x9932CC)
    public static let darkRed = Color(hex: 0x8B0000)
    public static let darkSalmon = Color(hex: 0xE9967A)
    public static let darkSeaGreen = Color(hex: 0x8FBC8F)
    public static let darkSlateBlue = Color(hex: 0x483D8B)
    public static let darkSlateGray = Color(hex: 0x2F4F4F)
    public static let darkTurqoise = Color(hex: 0x00CED1)
    public static let darkViolet = Color(hex: 0x9400D3)
    public static let deepPink = Color(hex: 0xFF1493)
    public static let deepSkyBlue = Color(hex: 0x00BFFF)
    public static let dimGray = Color(hex: 0x696969)
    public static let dodgerBlue = Color(hex: 0x1E90FF)
    public static let fireBrick = Color(hex: 0xB22222)
    public static let floralWhite = Color(hex: 0xFFFAF0)
    public static let forestGreen = Color(hex: 0x228B22)
    public static let fuchsia = Color(hex: 0xFF00FF)
    public static let gainsboro = Color(hex: 0xDCDCDC)
    public static let ghostWhite = Color(hex: 0xF8F8FF)
    public static let gold = Color(hex: 0xFFD700)
    public static let goldenRod = Color(hex: 0xDAA520)
    public static let gray = Color(hex: 0x808080)
    public static let green = Color(hex: 0x008000)
    public static let greenYellow = Color(hex: 0xADFF2F)
    public static let honeyDew = Color(hex: 0xF0FFF0)
    public static let hotPink = Color(hex: 0xFF69B4)
    public static let indianRed = Color(hex: 0xCD5C5C)
    public static let indigo = Color(hex: 0x4B0082)
    public static let ivory = Color(hex: 0xFFFFF0)
    public static let khaki = Color(hex: 0xF0E68C)
    public static let lavender = Color(hex: 0xE6E6FA)
    public static let lavenderBlush = Color(hex: 0xFFF0F5)
    public static let lawnGreen = Color(hex: 0x7CFC00)
    public static let lemonChiffon = Color(hex: 0xFFFACD)
    public static let lightBlue = Color(hex: 0xADD8E6)
    public static let lightCoral = Color(hex: 0xF08080)
    public static let lightCyan = Color(hex: 0xE0FFFF)
    public static let lightGoldenRodYellow = Color(hex: 0xFAFAD2)
    public static let lightGray = Color(hex: 0xD3D3D3)
    public static let lightGreen = Color(hex: 0x90EE90)
    public static let lightPink = Color(hex: 0xFFB6C1)
    public static let lightSalmon = Color(hex: 0xFFA07A)
    public static let lightSeaGreen = Color(hex: 0x20B2AA)
    public static let lightSkyBlue = Color(hex: 0x87CEFA)
    public static let lightSlateGray = Color(hex: 0x778899)
    public static let lightSteelBlue = Color(hex: 0xB0C4DE)
    public static let lightYellow = Color(hex: 0xFFFFE0)
    public static let lime = Color(hex: 0x00FF00)
    public static let limeGreen = Color(hex: 0x32CD32)
    public static let linen = Color(hex: 0xFAF0E6)
    public static let magenta = Color(hex: 0xFF00FF)
    public static let maroon = Color(hex: 0x800000)
    public static let mediumAquaMarine = Color(hex: 0x66CDAA)
    public static let mediumBlue = Color(hex: 0x0000CD)
    public static let mediumOrchid = Color(hex: 0xBA55D3)
    public static let mediumPurple = Color(hex: 0x9370DB)
    public static let mediumSeaGreen = Color(hex: 0x3CB371)
    public static let mediumSlateBlue = Color(hex: 0x7B68EE)
    public static let mediumSpringGreen = Color(hex: 0x00FA9A)
    public static let mediumTurquoise = Color(hex: 0x48D1CC)
    public static let mediumVioletRed = Color(hex: 0xC71585)
    public static let midnightBlue = Color(hex: 0x191970)
    public static let mintCream = Color(hex: 0xF5FFFA)
    public static let mistyRose = Color(hex: 0xFFE4E1)
    public static let moccasin = Color(hex: 0xFFE4B5)
    public static let navajoWhite = Color(hex: 0xFFDEAD)
    public static let navy = Color(hex: 0x000080)
    public static let oldLace = Color(hex: 0xFDF5E6)
    public static let olive = Color(hex: 0x808000)
    public static let oliveDrab = Color(hex: 0x6B8E23)
    public static let orange = Color(hex: 0xFFA500)
    public static let orangeRed = Color(hex: 0xFF4500)
    public static let orchid = Color(hex: 0xDA70D6)
    public static let paleGoldenRod = Color(hex: 0xEEE8AA)
    public static let paleGreen = Color(hex: 0x98FB98)
    public static let paleTurquoise = Color(hex: 0xAFEEEE)
    public static let paleVioletRed = Color(hex: 0xDB7093)
    public static let papayaWhip = Color(hex: 0xFFEFD5)
    public static let peachPuff = Color(hex: 0xFFDAB9)
    public static let peru = Color(hex: 0xCD853F)
    public static let pink = Color(hex: 0xFFC0CB)
    public static let plum = Color(hex: 0xDDA0DD)
    public static let powderBlue = Color(hex: 0xB0E0E6)
    public static let purple = Color(hex: 0x800080)
    public static let rebeccaPurple = Color(hex: 0x663399)
    public static let red = Color(hex: 0xFF0000)
    public static let rosyBrown = Color(hex: 0xBC8F8F)
    public static let royalBlue = Color(hex: 0x4169E1)
    public static let saddleBrown = Color(hex: 0x8B4513)
    public static let salmon = Color(hex: 0xFA8072)
    public static let sandyBrown = Color(hex: 0xF4A460)
    public static let seaGreen = Color(hex: 0x2E8B57)
    public static let seaShell = Color(hex: 0xFFF5EE)
    public static let sienna = Color(hex: 0xA0522D)
    public static let silver = Color(hex: 0xC0C0C0)
    public static let skyBlue = Color(hex: 0x87CEEB)
    public static let slateBlue = Color(hex: 0x6A5ACD)
    public static let slateGray = Color(hex: 0x708090)
    public static let snow = Color(hex: 0xFFFAFA)
    public static let springGreen = Color(hex: 0x00FF7F)
    public static let steelBlue = Color(hex: 0x4682B4)
    public static let tan = Color(hex: 0xD2B48C)
    public static let teal = Color(hex: 0x008080)
    public static let thistle = Color(hex: 0xD8BFD8)
    public static let tomato = Color(hex: 0xFF6347)
    public static let turquoise = Color(hex: 0x40E0D0)
    public static let violet = Color(hex: 0xEE82EE)
    public static let wheat = Color(hex: 0xF5DEB3)
    public static let white = Color(hex: 0xFFFFFF)
    public static let whiteSmoke = Color(hex: 0xF5F5F5)
    public static let yellow = Color(hex: 0xFFFF00)
    public static let yellowGreen = Color(hex: 0x9ACD32)
}

extension Color {
    public init(hex: Int) {
        self.init(
            red: Double((hex >> 16) & 0xFF) / 255,
            green: Double((hex >> 8) & 0xFF) / 255,
            blue: Double(hex & 0xFF) / 255
        )
    }
}
