coverage:
  ignore:
    - "Sources/PhantomKitLogger"
    - "Sources/PhantomKitNetworking"
    - "Sources/PhantomKitUI"
    - "Tests"
  status:
    project:
      default:
        target: 95%
        threshold: 3%
