coverage:
  ignore:
    - "Sources/PhantomKitAPI"
    - "Sources/PhantomKitLog"
    - "Sources/PhantomKitUI"
    - "Tests"
  status:
    project:
      default:
        target: 95%
        threshold: 3%
