coverage:
  ignore:
    - "Sources/PhantomKitUI"
    - "Tests"
  status:
    project:
      default:
        target: 95%
        threshold: 2%
    patch:
      default:
        target: 95%
        threshold: 2%
