name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer

  SCHEME: PhantomKit
  IOS_SDK: iphonesimulator
  IOS_DESTINATION: "platform=iOS Simulator,name=iPhone 13 Pro,OS=latest"
  DERIVED_DATA_PATH: build

jobs:
  build:
    runs-on: macos-11

    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: unit tests
        run: |
           set -o pipefail
           xcodebuild clean build test \
             -scheme "$SCHEME" \
             -sdk "$IOS_SDK" \
             -destination "$IOS_DESTINATION" \
             -enableCodeCoverage YES | xcpretty -c
      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          verbose: true
