name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run:  xcodebuild -scheme PhantomKit build -sdk iphonesimulator
    - name: Run tests
      run:  xcodebuild -scheme PhantomKit test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=Any iOS Simulator Device'
