name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run:  xcodebuild -scheme PhantomKit build -sdk iphonesimulator -configuration Release
    - name: Run tests
      run:  xcodebuild -scheme PhantomKitTests test -sdk iphonesimulator -configuration Release -destination 'platform=iOS Simulator,name=iPhone 12 Pro'
